import { lang } from './lang.ts';

// Vietnamese for the English terms used across the UI. In Vietnamese mode each term is
// replaced by its meaning; English mode shows the terms as written. Dataset values are kept.
export const SHOW_ENGLISH_HINTS = true;
const meanings: Record<string, string> = {
  'SmartReview Projects': 'Dự án SmartReview',
  Projects: 'Dự án',
  Project: 'Dự án',
  'New Project': 'Dự án mới',
  'Current Project': 'Dự án hiện tại',
  'Project Name': 'Tên dự án',
  'Description (optional)': 'Mô tả, không bắt buộc',
  Description: 'Mô tả',
  'Annotation Format': 'Định dạng nhãn',
  'Annotation File': 'Tệp nhãn',
  'Media images': 'Ảnh dữ liệu',
  'Media folder': 'Thư mục ảnh',
  'Create & Import': 'Tạo và nhập dữ liệu',
  'Import Dataset': 'Nhập bộ dữ liệu',
  'Start Review': 'Bắt đầu kiểm tra',
  'Save Review': 'Lưu đánh giá',
  'Update Review': 'Cập nhật đánh giá',
  'Correct / False Alarm': 'Nhãn đúng / cảnh báo nhầm',
  'Annotation Error': 'Lỗi gán nhãn',
  Unsure: 'Chưa chắc chắn',
  'Error Type': 'Loại lỗi',
  'Current Label': 'Nhãn hiện tại',
  'Correct Label': 'Nhãn đúng đề xuất',
  'Correction (optional)': 'Đề xuất sửa, không bắt buộc',
  'Note (optional)': 'Ghi chú, không bắt buộc',
  'Missing Object': 'Thiếu đối tượng',
  'Extra Object': 'Thừa đối tượng',
  Tracking: 'Theo dõi đối tượng',
  Class: 'Loại đối tượng',
  BBox: 'Khung bao',
  Other: 'Khác',
  'Total Risk Cases': 'Tổng trường hợp đáng nghi',
  'Risk Cases': 'Trường hợp đáng nghi',
  'Suspicious cases': 'Trường hợp đáng nghi',
  'Confirmed Errors': 'Lỗi đã xác nhận',
  'Confirmed Error': 'Lỗi đã xác nhận',
  Reviewed: 'Đã kiểm tra',
  Unreviewed: 'Chưa kiểm tra',
  Remaining: 'Còn lại',
  High: 'Cao',
  Medium: 'Trung bình',
  Low: 'Thấp',
  Progress: 'Tiến độ',
  'Review progress': 'Tiến độ kiểm tra',
  'Review Decision': 'Quyết định đánh giá',
  'Review Queue': 'Hàng đợi kiểm tra',
  'Annotation Inspector': 'Xem chi tiết nhãn',
  'Annotation Details': 'Chi tiết nhãn',
  'Annotation quality review': 'Kiểm tra chất lượng nhãn',
  'Annotation Quality Assurance': 'Đảm bảo chất lượng nhãn',
  'ANNOTATION QA': 'Kiểm tra chất lượng nhãn',
  'Quality Review / Workspace': 'Không gian kiểm tra chất lượng',
  'Dataset Workspace': 'Không gian quản lý dữ liệu',
  'Annotated Dataset': 'Bộ dữ liệu đã gán nhãn',
  'Active Dataset': 'Bộ dữ liệu đang dùng',
  'Priority Queue': 'Hàng đợi ưu tiên',
  'QA Analysis': 'Phân tích chất lượng',
  'QA checks': 'Kiểm tra chất lượng',
  'Engine Diagnostics': 'Thông tin bộ kiểm tra',
  'Check coverage': 'Phạm vi kiểm tra',
  'CHECK MODULE': 'Mô-đun kiểm tra',
  PASSED: 'Đạt',
  FLAGGED: 'Có cảnh báo',
  SKIPPED: 'Đã bỏ qua',
  'Why flagged': 'Vì sao bị cảnh báo',
  'Temporal context': 'Ngữ cảnh theo thời gian',
  Previous: 'Trước',
  Current: 'Hiện tại',
  Next: 'Sau',
  Evidence: 'Bằng chứng',
  Confidence: 'Độ tin cậy',
  Geometry: 'Hình dạng',
  Source: 'Nguồn',
  Label: 'Nhãn',
  Dataset: 'Bộ dữ liệu',
  Annotations: 'Nhãn',
  Annotation: 'Nhãn',
  Frames: 'Khung hình',
  Frame: 'Khung hình',
  Tracks: 'Chuỗi theo dõi',
  Track: 'Chuỗi theo dõi',
  Object: 'Đối tượng',
  Media: 'Dữ liệu ảnh',
  Format: 'Định dạng',
  Schema: 'Cấu trúc dữ liệu',
  Engine: 'Bộ xử lý',
  Risk: 'Rủi ro',
  Review: 'Kiểm tra',
  'Import Failed': 'Nhập dữ liệu thất bại',
  Ready: 'Sẵn sàng',
  Import: 'Nhập dữ liệu',
  Upload: 'Tải lên',
  Uploading: 'Đang tải lên',
  Validate: 'Kiểm tra tính hợp lệ',
  Save: 'Lưu',
  Case: 'Trường hợp',
  Cases: 'Trường hợp',
  'N/A': 'Không có',
  'AI Check': 'Kiểm tra AI',
  'Risk Engine': 'Bộ chấm rủi ro',
  'Risk Case': 'Trường hợp rủi ro',
  Datasets: 'Bộ dữ liệu',
  Severity: 'Mức độ',
  Workspace: 'Không gian làm việc',
  Observation: 'Quan sát',
  Metrics: 'Số liệu',
  'Independent of models': 'Không phụ thuộc mô hình',
  'Human-led review': 'Con người thực hiện đánh giá',
};

const lookup = Object.fromEntries(Object.entries(meanings).map(([k, v]) => [k.toLowerCase(), v]));
const escaped = Object.keys(meanings)
  .sort((a, b) => b.length - a.length)
  .map((k) => k.replaceAll('(', '\\(').replaceAll(')', '\\)'));
const pattern = new RegExp('\\b(' + escaped.join('|') + ')(?![A-Za-z])', 'gi');
// The meaning takes the case of the term it replaces: "frame" inside a sentence, "PASSED" in a header.
function fit(word: string, meaning: string) {
  if (word.length >= 5 && word === word.toUpperCase()) return meaning.toUpperCase();
  return word[0] === word[0].toLowerCase() ? meaning[0].toLowerCase() + meaning.slice(1) : meaning;
}
export const replaceTerms = (text: string) =>
  text.replace(pattern, (word) => fit(word, lookup[word.toLowerCase()]));
export function hint<T>(text: T): T {
  if (!SHOW_ENGLISH_HINTS || lang === 'en' || typeof text !== 'string') return text;
  return replaceTerms(text) as T;
}
